[package]
name = "autoclicker"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1.3"
parse_duration = "2.1.1"
rustop = "1.1.4"
